-- MySQL Script generated by MySQL Workbench
-- mer. 18 déc. 2019 14:26:33 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema micropousses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema micropousses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `micropousses` DEFAULT CHARACTER SET utf8 ;
USE `micropousses` ;

-- -----------------------------------------------------
-- Table `micropousses`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micropousses`.`Client` (
  `ID_CL` INT NOT NULL AUTO_INCREMENT,
  `CL_nom` VARCHAR(45) NULL,
  `CL_adresse` VARCHAR(255) NULL,
  `CL_code_postal` VARCHAR(5) NULL,
  `CL_ville` VARCHAR(100) NULL,
  `CL_tel` VARCHAR(10) NULL,
  `CL_mail` VARCHAR(105) NULL,
  PRIMARY KEY (`ID_CL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micropousses`.`Commande_Matériels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micropousses`.`Commande_Matériels` (
  `ID_CM` INT NOT NULL AUTO_INCREMENT,
  `CM_date_commande` DATE NULL,
  `CM_date_livraison` DATE NULL,
  `CM_prix_unitaire` FLOAT NULL,
  `CM_prix_total` FLOAT NULL,
  PRIMARY KEY (`ID_CM`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micropousses`.`Fournisseur_matériels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micropousses`.`Fournisseur_matériels` (
  `ID_FM` INT NOT NULL AUTO_INCREMENT,
  `FM_nom` VARCHAR(50) NULL,
  `FM_adresse` VARCHAR(255) NULL,
  `FM_ville` VARCHAR(5) NULL,
  `FM_tel` VARCHAR(10) NULL,
  `FM_numéro_siret` VARCHAR(20) NULL,
  `FM_mail` VARCHAR(50) NULL,
  `Commande_Matériels_ID_CM` INT NOT NULL,
  PRIMARY KEY (`ID_FM`, `Commande_Matériels_ID_CM`),
  INDEX `fk_Fournisseur_matériels_Commande_Matériels1_idx` (`Commande_Matériels_ID_CM` ASC),
  CONSTRAINT `fk_Fournisseur_matériels_Commande_Matériels1`
    FOREIGN KEY (`Commande_Matériels_ID_CM`)
    REFERENCES `micropousses`.`Commande_Matériels` (`ID_CM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micropousses`.`Commande_graines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micropousses`.`Commande_graines` (
  `ID_CG` INT NOT NULL AUTO_INCREMENT,
  `CG_commande` VARCHAR(45) NULL,
  `CG_date_commande` DATE NULL,
  `CG_date_livraison` DATE NULL,
  `CG_quantité` INT NULL,
  `CG_prix` FLOAT NULL,
  PRIMARY KEY (`ID_CG`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micropousses`.`Paysan_Urbain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micropousses`.`Paysan_Urbain` (
  `ID_PU` INT NOT NULL AUTO_INCREMENT,
  `PU_nom` VARCHAR(20) NULL,
  `PU_adresse` VARCHAR(250) NULL,
  `PU_TEL` VARCHAR(10) NULL,
  `PU_mail` VARCHAR(50) NULL,
  `Commande_graines_ID_CG` INT NOT NULL,
  `Commande_Matériels_ID_CM` INT NOT NULL,
  PRIMARY KEY (`ID_PU`, `Commande_Matériels_ID_CM`),
  INDEX `fk_Paysan_Urbain_Commande_graines1_idx` (`Commande_graines_ID_CG` ASC),
  INDEX `fk_Paysan_Urbain_Commande_Matériels1_idx` (`Commande_Matériels_ID_CM` ASC),
  CONSTRAINT `fk_Paysan_Urbain_Commande_graines1`
    FOREIGN KEY (`Commande_graines_ID_CG`)
    REFERENCES `micropousses`.`Commande_graines` (`ID_CG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paysan_Urbain_Commande_Matériels1`
    FOREIGN KEY (`Commande_Matériels_ID_CM`)
    REFERENCES `micropousses`.`Commande_Matériels` (`ID_CM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micropousses`.`Commande_Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micropousses`.`Commande_Clients` (
  `ID_CC` INT NOT NULL AUTO_INCREMENT,
  `CC_date_commande` DATE NULL,
  `CC_date_livraison` DATE NULL,
  `CC_prix` INT NULL,
  `Client_ID_CL` INT NOT NULL,
  PRIMARY KEY (`ID_CC`),
  INDEX `fk_Commande_Clients_Client_idx` (`Client_ID_CL` ASC),
  CONSTRAINT `fk_Commande_Clients_Client`
    FOREIGN KEY (`Client_ID_CL`)
    REFERENCES `micropousses`.`Client` (`ID_CL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micropousses`.`Fournisseur_Graines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micropousses`.`Fournisseur_Graines` (
  `iD_FG` INT NOT NULL AUTO_INCREMENT,
  `FG_numero_siret` VARCHAR(50) NULL,
  `FG_nom` VARCHAR(250) NULL,
  `FG_adresse` VARCHAR(50) NULL,
  `FG_ville` VARCHAR(10) NULL,
  `FG_ tel` VARCHAR(100) NULL,
  `Commande_graines_ID_CG` INT NOT NULL,
  PRIMARY KEY (`iD_FG`, `Commande_graines_ID_CG`),
  INDEX `fk_Fournisseur_Graines_Commande_graines1_idx` (`Commande_graines_ID_CG` ASC),
  CONSTRAINT `fk_Fournisseur_Graines_Commande_graines1`
    FOREIGN KEY (`Commande_graines_ID_CG`)
    REFERENCES `micropousses`.`Commande_graines` (`ID_CG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micropousses`.`Matériels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micropousses`.`Matériels` (
  `ID_MA` INT NOT NULL AUTO_INCREMENT,
  `MA_nom` VARCHAR(10) NULL,
  `MA_quantité` FLOAT NULL,
  `Fournisseur_matériels_ID_FM` INT NOT NULL,
  PRIMARY KEY (`ID_MA`),
  INDEX `fk_Matériels_Fournisseur_matériels1_idx` (`Fournisseur_matériels_ID_FM` ASC),
  CONSTRAINT `fk_Matériels_Fournisseur_matériels1`
    FOREIGN KEY (`Fournisseur_matériels_ID_FM`)
    REFERENCES `micropousses`.`Fournisseur_matériels` (`ID_FM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micropousses`.`Graines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micropousses`.`Graines` (
  `ID_GR` INT NOT NULL,
  `GR_nom` VARCHAR(45) NULL,
  `GR_quantité` INT NULL,
  `Fournisseur_Graines_iD_FG` INT NOT NULL,
  `Matériels_ID_MA` INT NOT NULL,
  PRIMARY KEY (`ID_GR`, `Fournisseur_Graines_iD_FG`, `Matériels_ID_MA`),
  INDEX `fk_Graines_Fournisseur_Graines1_idx` (`Fournisseur_Graines_iD_FG` ASC),
  INDEX `fk_Graines_Matériels1_idx` (`Matériels_ID_MA` ASC),
  CONSTRAINT `fk_Graines_Fournisseur_Graines1`
    FOREIGN KEY (`Fournisseur_Graines_iD_FG`)
    REFERENCES `micropousses`.`Fournisseur_Graines` (`iD_FG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Graines_Matériels1`
    FOREIGN KEY (`Matériels_ID_MA`)
    REFERENCES `micropousses`.`Matériels` (`ID_MA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micropousses`.`Microupousse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micropousses`.`Microupousse` (
  `ID_MP` INT NOT NULL AUTO_INCREMENT,
  `MP_NOM` VARCHAR(50) NULL,
  `MP_quantité` VARCHAR(10) NULL,
  `MP_prix` FLOAT NULL,
  `MP_date_plantation` DATE NULL,
  `MP_date_recolte` DATE NULL,
  `Commande_Clients_ID_CC` INT NOT NULL,
  `Graines_ID_GR` INT NOT NULL,
  PRIMARY KEY (`ID_MP`, `Graines_ID_GR`),
  INDEX `fk_Microupousse_Commande_Clients1_idx` (`Commande_Clients_ID_CC` ASC),
  INDEX `fk_Microupousse_Graines1_idx` (`Graines_ID_GR` ASC),
  CONSTRAINT `fk_Microupousse_Commande_Clients1`
    FOREIGN KEY (`Commande_Clients_ID_CC`)
    REFERENCES `micropousses`.`Commande_Clients` (`ID_CC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Microupousse_Graines1`
    FOREIGN KEY (`Graines_ID_GR`)
    REFERENCES `micropousses`.`Graines` (`ID_GR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
